AbstergoCommerce.WebUI/Controllers/AdminController.cs
using AbstergoCommerce.WebUI.App_Class;
using AbstergoCommerce.WebUI.Models;
using System;
using System.Configuration;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Image = System.Drawing.Image;

namespace AbstergoCommerce.WebUI.Controllers
{
    public class AdminController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Products()
        {
            return View(db.Products.ToList());
        }


        public ActionResult Create()
        {
            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Brands = db.Brands.ToList();

            return View();
        }

        [HttpPost]
        public ActionResult Create(Product product)
        {

            db.Products.Add(product);
            db.SaveChanges();

            return RedirectToAction("Products");
        }

        public ActionResult Brands()
        {
            return View(db.Brands.ToList());
        }

        public ActionResult CreateBrand()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateBrand(Brand brand, HttpPostedFileBase fileUpload)
        {
            int imgId = -1;
            if (fileUpload != null)
            {
                Image img = Image.FromStream(fileUpload.InputStream);
                int width = Convert.ToInt32(ConfigurationManager.AppSettings["BrandWidth"].ToString());
                int height = Convert.ToInt32(ConfigurationManager.AppSettings["BrandHeight"].ToString());

                string name = "/Content/BrandImage/" + Guid.NewGuid() + Path.GetExtension(fileUpload.FileName);

                Bitmap bmp = new Bitmap(img, width, height);
                bmp.Save(Server.MapPath(name));

                Models.Image pic = new Models.Image { MedUrl = name };
                db.Images.Add(pic);
                db.SaveChanges();
                if (pic.Id != null)
                    imgId = pic.Id;
            }
            if (imgId != -1)
                brand.ImageID = imgId;
            db.Brands.Add(brand);
            db.SaveChanges();

            return RedirectToAction("Brands");
        }

        public ActionResult Categories()
        {
            return View(db.Categories.ToList());
        }

        public ActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateCategory(Category category)
        {
            db.Categories.Add(category);
            db.SaveChanges();
            return RedirectToAction("Categories");
        }

        public ActionResult SpecTypes()
        {
            return View(db.SpecificationTypes.ToList());
        }

        public ActionResult SpecTypeCreate()
        {
            return View(db.Categories.ToList());
        }

        [HttpPost]
        public ActionResult SpecTypeCreate(SpecificationType type)
        {
            db.SpecificationTypes.Add(type);
            db.SaveChanges();
            return RedirectToAction("SpecTypes");

        }

        public ActionResult Specifications()
        {
            return View(db.Specifications.ToList());
        }

        public ActionResult SpecificationCreate()
        {
            return View(db.SpecificationTypes.ToList());
        }

        [HttpPost]
        public ActionResult SpecificationCreate(Specification spec)
        {
            db.Specifications.Add(spec);
            db.SaveChanges();
            return RedirectToAction("Specifications");
        }

        public ActionResult ProductSpecifications()
        {
            return View(db.ProductSpecifications.ToList());
        }

        public ActionResult ProductSpecDelete(int productId, int typeId, int specId)
        {
            ProductSpecification ps = db.ProductSpecifications
                .FirstOrDefault(x => x.ProductID == productId
                                     && x.SpecTypeID == typeId && x.SpecificationID == specId);

            db.ProductSpecifications.Remove(ps);
            db.SaveChanges();
            return RedirectToAction("ProductSpecifications");
        }

        public ActionResult ProductSpecCreate()
        {
            return View(db.Products.ToList());
        }

        public PartialViewResult ProductSpecTypeWidget(int? catId)
        {
            if (catId != null)
            {
                var data = db.SpecificationTypes.Where(x => x.CategoryID == catId).ToList();
                return PartialView(data);
            }
            else
            {
                var data = db.SpecificationTypes.ToList();
                return PartialView(data);
            }
        }

        public PartialViewResult ProdutSpecWidget(int? typeId)
        {
            if (typeId != null)
            {
                var data = db.Specifications.Where(x => x.SpecTypeID == typeId);
                return PartialView(data);
            }
            else
            {
                var data = db.Specifications.ToList();
                return PartialView(data);
            }
        }

        [HttpPost]
        public ActionResult ProductSpecCreate(ProductSpecification ps)
        {
            db.ProductSpecifications.Add(ps);
            db.SaveChanges();
            return RedirectToAction("ProductSpecifications");
        }

        public ActionResult ImageAdd(int id)
        {
            return View(id);
        }

        [HttpPost]
        public ActionResult ImageAdd(int pId, HttpPostedFileBase fileUpload)
        {
            if (fileUpload != null)
            {
                Image img = Image.FromStream(fileUpload.InputStream);
                Bitmap medImage = new Bitmap(img, Settings.ProductMediumSize);
                Bitmap bigImage = new Bitmap(img, Settings.ProductBigSize);

                string medUrl = "/Content/ProductImage/Medium/" + Guid.NewGuid() +
                    Path.GetExtension(fileUpload.FileName);

                string bigUrl = "/Content/ProductImage/Big/" + Guid.NewGuid() +
                    Path.GetExtension(fileUpload.FileName);

                medImage.Save(Server.MapPath(medUrl));
                bigImage.Save(Server.MapPath(bigUrl));

                Models.Image image = new Models.Image
                {
                    BigUrl = bigUrl,
                    MedUrl = medUrl,
                    ProductID = pId
                };
                if (db.Images.FirstOrDefault(x => x.ProductID == pId && x.Defaault == false) != null)
                    image.Defaault = true;
                else
                    image.Defaault = false;
                db.Images.Add(image);
                db.SaveChanges();
                return View(pId);
            }
            return View(pId);
        }

        public ActionResult SliderImages()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SliderImageAdd(HttpPostedFileBase fileUpload)
        {

            if (fileUpload != null)
            {
                Image img = Image.FromStream(fileUpload.InputStream);
                Bitmap bmp = new Bitmap(img, Settings.SliderImageSize);

                string Url = "/Content/SliderImage/" + Guid.NewGuid() +
                   Path.GetExtension(fileUpload.FileName);

                bmp.Save(Server.MapPath(Url));

                Models.Image image = new Models.Image
                {
                    BigUrl = Url
                };
                db.Images.Add(image);
                db.SaveChanges();
            }
            return RedirectToAction("SliderImages");
        }
    }
}

AbstergoCommerce.WebUI/Controllers/UserController.cs
using System.Web.Mvc;

namespace AbstergoCommerce.WebUI.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Account()
        {
            return View();
        }

        public ActionResult Login()
        {
            throw new System.NotImplementedException();
        }

        public ActionResult Logout()
        {
            throw new System.NotImplementedException();
        }

        public ActionResult Register()
        {
            throw new System.NotImplementedException();
        }
    }
}

AbstergoCommerce.WebUI/Views/Shared/AdminLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="img/favicon.png">

    <title>Abstergo Commerce - @ViewBag.Title</title>

    <!-- Bootstrap core CSS -->
    <link href="/Content/Admin/css/bootstrap.min.css" rel="stylesheet">
    <link href="/Content/Admin/css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="/Content/Admin/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="/Content/Admin/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen" />
    <link rel="stylesheet" href="/Content/Admin/css/owl.carousel.css" type="text/css">
    <!-- Custom styles for this template -->
    <link href="/Content/Admin/css/style.css" rel="stylesheet">
    <link href="/Content/Admin/css/style-responsive.css" rel="stylesheet" />

   @RenderSection("head",false)
</head>

<body>

    <section id="container" >
        <!--header start-->
        <header class="header white-bg">
            <div class="sidebar-toggle-box">
                <div data-original-title="Toggle Navigation" data-placement="right" class="icon-reorder tooltips"></div>
            </div>
            <!--logo start-->
            <a href="/Admin/Index" class="logo">Abstergo<span>Commerce</span></a>
            <!--logo end-->
            <div class="nav notify-row" id="top_menu">
              
            </div>
            <div class="top-nav ">
                <!--search & user info start-->
                <ul class="nav pull-right top-menu">
                    <li>
                        <input type="text" class="form-control search" placeholder="Search">
                    </li>
                 
                </ul>
                <!--search & user info end-->
            </div>
        </header>
        <!--header end-->
        <!--sidebar start-->
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu" id="nav-accordion">
                    <li>
                        <a class="active" href="@Url.Action("Index","Admin")">
                            <i class="icon-dashboard"></i>
                            <span>Homepage</span>
                        </a>
                    </li>
                    <li>
                        <a class="active" href="@Url.Action("Products","Admin")">
                            <i class="icon-picture"></i>
                            <span>Products</span>
                        </a>
                    </li>
                    <li>
                        <a class="active" href="@Url.Action("Categories","Admin")">
                            <i class="icon-food"></i>
                            <span>Categories</span>
                        </a>
                    </li>
                    <li>
                        <a class="active" href="@Url.Action("Brands","Admin")">
                            <i class="icon-certificate"></i>
                            <span>Brands</span>
                        </a>
                    </li>
                    <li>
                        <a class="active" href="@Url.Action("Customers","Admin")">
                            <i class="icon-user"></i>
                            <span>Customers</span>
                        </a>
                    </li>
                    <li>
                        <a class="active" href="@Url.Action("SliderImages","Admin")">
                            <i class="icon-film"></i>
                            <span>Slider Images</span>
                        </a>
                    <li class="sub-menu">
                        <a href="javascript:;">
                            <i class="icon-laptop"></i>
                            <span>Specification</span>
                        </a>
                        <ul class="sub">
                            <li><a href="@Url.Action("SpecTypes","Admin")">Types</a></li>
                            <li><a href="@Url.Action("Specifications","Admin")">Specifications</a></li>
                            <li><a href="@Url.Action("ProductSpecifications","Admin")">Product Specifications</a></li>
                        </ul>
                    </li>
                    </li>


                    <li class="sub-menu">
                        <a href="javascript:;">
                            <i class="icon-laptop"></i>
                            <span>Shopping</span>
                        </a>
                        <ul class="sub">
                            <li><a href="/Admin/CompletedOrders">Completed Orders</a></li>
                            <li><a href="/Admin/PendingOrders">Pending approval orders</a></li>
                            <li><a href="/Admin/CargoOrders">Cargo Orders</a></li>
                        </ul>
                    </li>

                    <li class="sub-menu">
                        <a href="javascript:;">
                            <i class="icon-book"></i>
                            <span>Reports</span>
                        </a>
                        <ul class="sub">
                            <li><a href="/Admin/ProductReports">Product Reports</a></li>
                            <li><a href="/Admin/SaleReports">Sale Reports</a></li>
                            <li><a href="/Admin/CustomerReports">Customer Reports</a></li>
                        </ul>
                    </li>

                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
           @RenderBody()
        </section>
        <!--main content end-->
        <!--footer start-->
        
        <!--footer end-->
    </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="/Content/Admin/js/jquery.js"></script>
    <script src="/Content/Admin/js/jquery-1.8.3.min.js"></script>
    <script src="/Content/Admin/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="/Content/Admin/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="/Content/Admin/js/jquery.scrollTo.min.js"></script>
    <script src="/Content/Admin/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="/Content/Admin/js/jquery.sparkline.js" type="text/javascript"></script>
    <script src="/Content/Admin/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>
    <script src="/Content/Admin/js/owl.carousel.js"></script>
    <script src="/Content/Admin/js/jquery.customSelect.min.js"></script>
    <script src="/Content/Admin/js/respond.min.js"></script>

    <script class="include" type="text/javascript" src="/Content/Admin/js/jquery.dcjqaccordion.2.7.js"></script>

    <!--common script for all pages-->
    <script src="/Content/Admin/js/common-scripts.js"></script>

    <!--script for this page-->
    <script src="/Content/Admin/js/sparkline-chart.js"></script>
    <script src="/Content/Admin/js/easy-pie-chart.js"></script>
    <script src="/Content/Admin/js/count.js"></script>

    <script>

      //owl carousel

      $(document).ready(function() {
          $("#owl-demo").owlCarousel({
              navigation : true,
              slideSpeed : 300,
              paginationSpeed : 400,
              singleItem : true,
			  autoPlay:true

          });
      });

      //custom select box

      $(function(){
          $('select.styled').customSelect();
      });

    </script>

</body>
</html>

AbstergoCommerce.WebUI/Views/Shared/SiteLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Zeon</title>
        <meta name="description" content="Here goes description" />
        <meta name="author" content="author name" />
        <link rel="shortcut icon" href="/Content/Zeon/images/favicon.ico" type="image/x-icon" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <link rel="stylesheet" href="/Content/Zeon/css/bootstrap.css" />    
        <link rel="stylesheet" href="/Content/Zeon/css/style.css" />
    </head>

<body class="home-blog-show">

    <div class="header">
        <div class="container">
         
            <div class="header-middle-info">
                <div class="col-md-4">
                    <div class="logo">
                        <a href="/Home/Index">
                            <img src="~/Content/PhyDetail-LocationWebsiteIcon.png" />
                        </a>
                    </div>
                </div>
                <div class="col-md-8">
                    <ul class="header-middle-account">
                        <li><a href="@Url.Action("Account", "User")"><i class="icon-330" title="My account"></i> My account</a></li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>
                                <a href="@Url.Action("Logout", "User")">
                                    <i class="icon-351" title="Login"></i> Logout
                                </a>
                            </li>
                        }
                        else
                        {
                            <li><a href="@Url.Action("Login","User")"><i class="icon-351" title="Login"></i> Login</a></li>
                        }
                    </ul>
                </div>
                <div class="clear"></div>
            </div>
            <div class="menu">
                <div class="search-cart">
                    <form class="search">
                        <input type="text" class="search-line" placeholder="Search" name="serch" />
                        <input type="submit" value="" class="search-button" />
                    </form>

                    @{
                        Html.RenderAction("Cart", "Home");
                    }
                    <div class="clear"></div>
                </div>
                <div class="repsonsive-menu"><i class="icon-406" title="406"></i> Menu</div>
                <ul>
                    <li class="menu-item-has-children active"><a href="@Url.Action("Index","Home")">Home</a></li>
                    <li><a href="@Url.Action("Categories","Home")">Categories</a></li>

                    <li class="menu-item-has-children">
                        <a href="#">Pages</a>
                        <ul>
                            <li><a href="@Url.Action("About","Home")">About Us</a></li>
                            <li><a href="@Url.Action("Register","User")">Register page</a></li>
                        </ul>
                    </li>
                    <li><a href="@Url.Action("Contact","Home")">Contact</a></li>
                </ul>
                <div class="clear"></div>
            </div>
        </div>
    </div>




    <div class="content">

        @{
            Html.RenderAction("Slider", "Home");
        }

        @{
            Html.RenderAction("NewProducts", "Home");
        }

        @RenderBody()

        @{
            Html.RenderAction("Services", "Home");
        }
        
        @{
            Html.RenderAction("Brands", "Home");
        }

    </div>
   

   
    <script src="/Content/Zeon/js/modernizr.custom.63321.js" type="text/javascript"></script>
    <script src="/Content/Zeon/js/jquery-1.10.0.min.js" type="text/javascript"></script>
    <script src="/Content/Zeon/js/jquery-ui.min.js" type="text/javascript"></script>
    <script src="/Content/Zeon/js/bootstrap.js" type="text/javascript"></script>
    <script src="/Content/Zeon/js/placeholder.js" type="text/javascript"></script>
    <script src="/Content/Zeon/js/imagesloaded.pkgd.min.js" type="text/javascript"></script>
    <script src="/Content/Zeon/js/masonry.pkgd.min.js" type="text/javascript"></script>
    <script src="/Content/Zeon/js/jquery.swipebox.min.js" type="text/javascript"></script>
    <script src="/Content/Zeon/js/farbtastic/farbtastic.js" type="text/javascript"></script>
    <script src="/Content/Zeon/js/options.js" type="text/javascript"></script>
    <script src="/Content/Zeon/js/plugins.js" type="text/javascript"></script>
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  
</body>


</html>